show_on:
  default: homepage
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out

show_title:
  default: true

title_text:
  default: "Active communities"

show_description:
  default: true

description_text:
  default: "We are trying to address the issues that people are concerned about right now, and together with the community we are trying to find the answers."
